INSERT INTO ESTADO(NOME,SIGLA,IBGE) VALUES('AMAZONAS', 'AM', '13');
--INSERT INTO ESTADO(NOME,SIGLA,IBGE) VALUES('RIO DE JANEIRO', 'RJ', '33');
--INSERT INTO ESTADO(NOME,SIGLA,IBGE) VALUES('SAO PAULO', 'SP', '35');


INSERT INTO CIDADE(NOME,IBGE,ESTADO_ID) VALUES('MANAUS', '1300', 1);
--INSERT INTO CIDADE(NOME,IBGE,ESTADO_ID) VALUES('RIO DE JANEIRO', '3300', 2);
--INSERT INTO CIDADE(NOME,IBGE,ESTADO_ID) VALUES('SAO PAULO', '3500', 3);

INSERT INTO PESSOA(NOME,TELEFONE,EMAIL, CIDADE_ID) VALUES('ALUNO1', '9299999999', 'ALUNO1.EMAIL@IFAM.EDU.BR',1);
INSERT INTO PESSOA(NOME,TELEFONE,EMAIL, CIDADE_ID) VALUES('ALUNO2', '9299999999', 'ALUNO2.EMAIL@IFAM.EDU.BR',1);
INSERT INTO PESSOA(NOME,TELEFONE,EMAIL, CIDADE_ID) VALUES('ALUNO3', '9999999999', 'ALUNO3.EMAIL@IFAM.EDU.BR',1);



